# Generated by Django 6.0.5 on 2026-06-29 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('ON_TRIP', 'ON_TRIP')], default='AVAILABLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'SCHEDULED'), ('COMPLETED', 'COMPLETED')], default='SCHEDULED', max_length=20)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('cab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rides.cab')),
            ],
        ),
    ]
