# Generated by Django 6.0.5 on 2026-07-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_remove_booking_rider_booking_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='driver_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_completed',
            field=models.BooleanField(default=False),
        ),
    ]
