# Generated by Django 6.0.5 on 2026-08-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_rideaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideaudit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
